name: marida
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.12.0=py37haa95532_0
  - affine=2.3.0=py_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blosc=1.21.0=h19a0ad4_0
  - boost-cpp=1.74.0=h54f0996_3
  - brotli=1.0.9=ha925a31_2
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2021.5.25=haa95532_1
  - certifi=2021.5.30=py37haa95532_0
  - charls=2.2.0=h6c2663c_0
  - click=7.1.2=pyhd3eb1b0_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=py37haa95532_0
  - cloudpickle=1.6.0=py_0
  - coverage=5.5=py37h2bbff1b_2
  - cudatoolkit=11.0.221=h74a9793_0
  - curl=7.68.0=h4496350_0
  - cycler=0.10.0=py37_0
  - cython=0.29.23=py37hd77b12b_0
  - cytoolz=0.11.0=py37he774522_0
  - dask-core=2021.5.1=pyhd3eb1b0_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - expat=2.4.1=h39d44d4_0
  - freetype=2.10.4=hd328e21_0
  - freexl=1.0.6=ha8e266a_0
  - fsspec=0.9.0=pyhd3eb1b0_0
  - gdal=2.3.3=py37hdf43c64_0
  - geos=3.7.1=h33f27b4_0
  - giflib=5.2.1=h62dcd97_0
  - grpcio=1.36.1=py37hc60d5dd_1
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.4=nompi_hcc15c50_1106
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - imagecodecs=2021.4.28=py37h5da4933_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - importlib-metadata=3.10.0=py37haa95532_0
  - intel-openmp=2021.2.0=haa95532_616
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=hb83a4c4_2
  - kealib=1.4.7=h07cbb95_6
  - kiwisolver=1.3.1=py37hd77b12b_0
  - krb5=1.16.4=hdd46e55_0
  - lcms2=2.12=h83e58a3_0
  - lerc=2.2.1=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libcurl=7.68.0=h4496350_0
  - libdeflate=1.7=h2bbff1b_5
  - libgdal=2.3.3=h10f50ba_0
  - libiconv=1.16=he774522_0
  - libnetcdf=4.6.1=h411e497_2
  - libpng=1.6.37=h2a8f88b_0
  - libpq=11.5=hb0bdaea_2
  - libprotobuf=3.14.0=h23ce68f_0
  - libspatialite=4.3.0a=h6a0152f_1026
  - libssh2=1.9.0=h680486a_6
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.40.0=he774522_0
  - libxml2=2.9.12=hf5bbc77_0
  - libzopfli=1.0.3=ha925a31_0
  - locket=0.2.1=py37haa95532_1
  - lz4-c=1.9.3=h2bbff1b_0
  - lzo=2.10=he774522_2
  - markdown=3.3.4=py37haa95532_0
  - matplotlib-base=3.3.4=py37h49ac443_0
  - mkl=2021.2.0=haa95532_296
  - mkl-service=2.3.0=py37h2bbff1b_1
  - mkl_fft=1.3.0=py37h277e83a_2
  - mkl_random=1.2.1=py37hf11a4ad_2
  - mock=4.0.3=pyhd3eb1b0_0
  - networkx=2.2=py37_1
  - ninja=1.10.2=h6d14046_1
  - numexpr=2.7.3=py37hb80d3ca_1
  - numpy=1.20.2=py37ha4e8547_0
  - numpy-base=1.20.2=py37hc2deb75_0
  - olefile=0.46=py37_0
  - openjpeg=2.3.0=h5ec785f_1
  - openssl=1.1.1k=h2bbff1b_0
  - pandas=1.2.4=py37hd77b12b_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pcre=8.44=ha925a31_0
  - pillow=8.2.0=py37h4fa10fc_0
  - pip=21.1.1=py37haa95532_0
  - proj4=5.2.0=h6538335_1006
  - protobuf=3.14.0=py37hd77b12b_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pytables=3.6.1=py37h1da0976_0
  - python=3.7.10=h6244533_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.7.0=py3.7_cuda110_cudnn8_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py37he774522_2
  - pyyaml=5.4.1=py37h2bbff1b_1
  - rasterio=1.0.21=py37h6bd7d87_0
  - scikit-image=0.18.1=py37hf11a4ad_0
  - scikit-learn=0.24.2=py37hf11a4ad_0
  - scipy=1.6.2=py37h66253e8_1
  - setuptools=52.0.0=py37haa95532_0
  - six=1.15.0=py37haa95532_0
  - snappy=1.1.8=h33f27b4_0
  - snuggs=1.4.7=py_0
  - sqlite=3.35.4=h2bbff1b_0
  - tensorboard=1.15.0=pyhb230dea_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2021.4.8=pyhd3eb1b0_2
  - tk=8.6.10=he774522_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - torchaudio=0.7.0=py37
  - torchvision=0.8.0=py37_cu110
  - tornado=6.1=py37h2bbff1b_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - webencodings=0.5.1=py37_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py37_0
  - xerces-c=3.2.3=h0e60522_2
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - zfp=0.5.5=hd77b12b_6
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
